# Generated by Django 3.1.4 on 2021-01-18 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=130, unique=True)),
                ('Content', models.TextField()),
                ('vieww', models.IntegerField(default=0)),
                ('photos', models.ImageField(blank=True, default='', upload_to='blog/image/')),
                ('video', models.FileField(blank=True, default='', upload_to='blog/video/')),
                ('rating', models.PositiveIntegerField(blank=True, default=0)),
                ('category', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('aboutperson', models.CharField(blank=True, default='', max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('aboutprofile', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('photo', models.ImageField(default='', upload_to='profile/image')),
                ('timeStamp1', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.blog')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.person')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.blog')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.person')),
            ],
        ),
    ]
